import { Category } from "@interfaces";

export const CATEGORY_LIST: Category[] = [
  { id: 1, name: "Alcohol/Bars", color: "#F97316", icon: "cocktail" },
  { id: 2, name: "Clothing", color: "#EC4899", icon: "shirt" },
  { id: 3, name: "Coffee/Snacks", color: "#A855F7", icon: "coffee" },
  { id: 4, name: "Debts", color: "#EF4444", icon: "banknotes" },
  { id: 5, name: "Dining Out", color: "#F59E0B", icon: "cake" },
  { id: 6, name: "Donations", color: "#34D399", icon: "heart" },
  { id: 7, name: "Education", color: "#F43F5E", icon: "academic-cap" },
  { id: 8, name: "Entertainment", color: "#C084FC", icon: "film" },
  { id: 9, name: "Events/Concerts", color: "#6366F1", icon: "ticket" },
  { id: 10, name: "Gifts", color: "#F87171", icon: "gift" },
  { id: 11, name: "Groceries", color: "#34D399", icon: "shopping-cart" },
  { id: 12, name: "Gym/Fitness", color: "#10B981", icon: "muscle" },
  { id: 13, name: "Health: Insurance", color: "#10B981", icon: "shield-check" },
  { id: 14, name: "Health: Medical", color: "#D97706", icon: "heart" },
  {
    id: 15,
    name: "Health: Therapy",
    color: "#A7F3D0",
    icon: "chat-bubble-oval-left",
  },
  { id: 16, name: "Holidays", color: "#EAB308", icon: "sun" },
  {
    id: 17,
    name: "Home Improvement",
    color: "#4B5563",
    icon: "building-storefront",
  },
  { id: 18, name: "Insurance", color: "#2563EB", icon: "shield-check" },
  { id: 19, name: "Investments", color: "#7C3AED", icon: "chart-pie" },
  { id: 20, name: "Language", color: "#FB7185", icon: "language" },
  { id: 21, name: "Personal Care", color: "#FB7185", icon: "sparkles" },
  { id: 22, name: "Pet Expenses", color: "#FBBF24", icon: "paw" },
  { id: 23, name: "Pharmacy", color: "#9333EA", icon: "capsule" },
  { id: 24, name: "Profile", color: "#9333EA", icon: "user" },
  { id: 25, name: "Rental", color: "#6B7280", icon: "home" },
  { id: 26, name: "Salary", color: "#16A34A", icon: "currency-dollar" },
  { id: 27, name: "Savings", color: "#4ADE80", icon: "chart-bar" },
  {
    id: 28,
    name: "Subscriptions",
    color: "#3B82F6",
    icon: "clipboard-document",
  },
  { id: 29, name: "Taxes", color: "#DC2626", icon: "receipt-tax" },
  { id: 30, name: "Technology", color: "#4F46E5", icon: "device-phone" },
  { id: 31, name: "Transport", color: "#A3E635", icon: "bus" },
  { id: 32, name: "Travel: Insurance", color: "#F472B6", icon: "shield-check" },
  { id: 33, name: "Travel: Tickets", color: "#FACC15", icon: "ticket" },
  {
    id: 34,
    name: "Unexpected Costs",
    color: "#F97316",
    icon: "exclamation-circle",
  },
  { id: 35, name: "Utilities", color: "#60A5FA", icon: "light-bulb" },
];
