import { Category } from "@interfaces";

export const CATEGORY_LIST: Category[] = [
  {
    id: 0,
    name: "Transfer between accounts",
    color: "#4189c4",
    icon: "FaReceipt",
  },
  { id: 1, name: "Bars", color: "#F97316", icon: "FaCocktail" },
  { id: 2, name: "Clothing", color: "#EC4899", icon: "FaTshirt" },
  { id: 3, name: "Coffee/Snacks", color: "#A855F7", icon: "FaCoffee" },
  { id: 4, name: "Debts", color: "#EF4444", icon: "FaMoneyBillWave" },
  { id: 5, name: "Dining Out", color: "#F59E0B", icon: "FaUtensils" },
  { id: 6, name: "Donations", color: "#34D399", icon: "FaHeart" },
  { id: 7, name: "Education", color: "#F43F5E", icon: "FaGraduationCap" },
  { id: 8, name: "Entertainment", color: "#C084FC", icon: "FaFilm" },
  { id: 9, name: "Events/Concerts", color: "#6366F1", icon: "FaTicketAlt" },
  { id: 10, name: "Gifts", color: "#F87171", icon: "FaGift" },
  { id: 11, name: "Groceries", color: "#34D399", icon: "FaShoppingCart" },
  { id: 12, name: "Gym/Fitness", color: "#10B981", icon: "FaDumbbell" },
  { id: 13, name: "Health: Insurance", color: "#10B981", icon: "FaShieldAlt" },
  { id: 14, name: "Health: Medical", color: "#D97706", icon: "FaHeartbeat" },
  { id: 15, name: "Health: Therapy", color: "#A7F3D0", icon: "FaComments" },
  { id: 16, name: "Holidays", color: "#EAB308", icon: "FaUmbrellaBeach" },
  { id: 17, name: "Home Improvement", color: "#4B5563", icon: "FaTools" },
  { id: 18, name: "Insurance", color: "#2563EB", icon: "FaShieldAlt" },
  { id: 19, name: "Investments", color: "#7C3AED", icon: "FaChartLine" },
  { id: 20, name: "Personal Care", color: "#FB7185", icon: "FaSpa" },
  { id: 21, name: "Pet Expenses", color: "#FBBF24", icon: "FaPaw" },
  { id: 22, name: "Pharmacy", color: "#9333EA", icon: "FaCapsules" },
  { id: 23, name: "Rental", color: "#6B7280", icon: "FaHome" },
  { id: 24, name: "Salary", color: "#16A34A", icon: "FaDollarSign" },
  { id: 25, name: "Savings", color: "#4ADE80", icon: "FaPiggyBank" },
  { id: 26, name: "Subscriptions", color: "#3B82F6", icon: "FaClipboardList" },
  { id: 27, name: "Taxes", color: "#DC2626", icon: "FaFileInvoiceDollar" },
  { id: 28, name: "Technology", color: "#4F46E5", icon: "FaLaptop" },
  { id: 29, name: "Transport", color: "#A3E635", icon: "FaBusAlt" },
  { id: 30, name: "Travel: Insurance", color: "#F472B6", icon: "FaShieldAlt" },
  { id: 31, name: "Travel: Tickets", color: "#FACC15", icon: "FaTicketAlt" },
  {
    id: 32,
    name: "Unexpected Costs",
    color: "#F97316",
    icon: "FaExclamationCircle",
  },
  { id: 33, name: "Utilities", color: "#60A5FA", icon: "FaLightbulb" },
];
